### PR TITLE
Django Login Backend

### PR DESCRIPTION
**Pull request by Octo-EN**
I don't know if your accepting pull requests yet, I know not everything is decided but I want to get the ball rolling. Created the backend for the Django Login system. Just needs a bit of redesigning to look better, I'll leave that to the UI/UX designing people.

### CODE REVIEW

**Comment by Octo-EN** [comment]
Should I add more commits? If we are going the Django route I can start working on a base chat and add in the cleverbot API later.

**Comment by Richard87** [comment]
Looking interrest! 

A few questions,
 - we where thinking about ading social login, is that easy to setup with Django?
 - Second, do you need any html at all if we are using a SPA, or is this just to simplify development?
 - In my head, I thought we would use json for all communication between the API and SPA, what do you think about that?
 - Also, we where thinking about leaving the login/auth to firebase, that means the backend needs to handle JSON Webtockens (to authenticate requests), or would you prefer to handle authentication/authorization in Django (If so we might have some issues with the realtime communication, but maybe you have some thoughts about that as well)?
 - We are probably going to need some Middleware to enable CORS since the API and SPA will have their own domain...

**Comment by Octo-EN** [comment]
OK cool. 
- I haven't done it before, but I'll see what can be done. 
- Just to simplify development.
- OK. I'll make changes and commit them by tomorrow.
- I'll think it over, read the documentations and see which would be easier.
- I'll research into it.

**Comment by Octo-EN** [comment]
I'll close this for now, when I've made changes I'll go from there.

**Comment by Richard87** [comment]
Alright, good luck!

**Pull request closed without merging**
